title: "Lukáš Hajdu"
baseurl: "http://lukashajdu.sk/"
publishDir: web
paginate: 20
disqusShortname: "lukashajdu-sk"
googleAnalytics: "UA-96014989-1"

params:
  sitename: "blog@lukash:/sk"
  dateform: "Monday, Jan 2, 2006"

theme: "hugo-black-and-light-theme"
PygmentsUseClasses: false
PygmentsCodeFences: true
PygmentsStyle: "friendly"

languageCode: "sk"
language: "sk"

taxonomies:
  tag: "tags"
  category: "categories"

menu:
  main:
    - name: "Blog"
      url: "/"
    - name: "O mne"
      url: "/o-mne/"
