title: "Lukáš Hajdu"
baseurl: "http://lukashajdu.sk/"
paginate: 20

params:
  sitename: "blog@lukas_hajdu:/sk"
  dateform: "1.2.2006"

theme: "hugo-black-and-light-theme"
PygmentsUseClasses: false
PygmentsCodeFences: true
PygmentsStyle: "friendly"

languageCode: "sk"
language: "sk"

taxonomies:
  tag: "tags"
  category: "categories"

menu:
  main:
    - name: "Blog"
      url: "/"
    - name: "O mne"
      url: "/o-mne/"