title: "Luk치코 Hajdu"
baseurl: "http://lukashajdu.sk/"

params:
  sitename: "Luk치코 Hajdu"
  dateform: "1.2.2006"

theme: "hugo-black-and-light-theme"
PygmentsUseClasses: false
PygmentsCodeFences: true
PygmentsStyle: "friendly"

languageCode: "sk"
language: "sk"
